sudo: false
language: node_js
node_js:
  - "12.18.2"
  - "14.5.0"
branches:
  only:
    - src
cache: yarn
script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - yarn
  - GIT_USER="${GH_NAME}" yarn deploy
